  const PhotographyData = [{
    fileName: "kyle-moseby-photography-thumb-03.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-04.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-05.jpg",
    title: 'Title',
  }, {
    fileName: "kyle-moseby-photography-thumb-06.jpg",
    title: 'Tester title',
  }, {
    fileName: "kyle-moseby-photography-thumb-07.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-08.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-09.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-10.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-11.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-12.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-13.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-14.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-15.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-16.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-17.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-18.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-19.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-20.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-21.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-22.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-23.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-24.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-25.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-26.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-27.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-28.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-29.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-30.jpg",
    title: '',
  }, {
    fileName: "kyle-moseby-photography-thumb-31.jpg",
    title: '',
  }];

  export default PhotographyData;
